# Generated by Django 5.0.6 on 2024-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('criteria_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
