# Generated by Django 5.0.6 on 2024-11-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_judge_delete_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='event_name',
            field=models.CharField(default='abhi', max_length=100),
            preserve_default=False,
        ),
    ]
