# Generated by Django 5.0.6 on 2024-11-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_lead_name', models.CharField(max_length=100)),
                ('cont_num', models.CharField(max_length=15)),
            ],
        ),
    ]
