# Generated by Django 5.0.6 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='event_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
