# Generated by Django 5.0.6 on 2024-11-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_studentdetail_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
