# Generated by Django 5.0.6 on 2024-11-07 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_studentdetail_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetail',
            options={'verbose_name': 'Student Detail', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='institute_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='participant_1',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='participant_2',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='participant_3',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cont_num',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='event_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='team_lead_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='team_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
