# Generated by Django 5.0.6 on 2024-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_alter_studentdetail_options_studentdetail_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='cont_num',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='institute_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='participant_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='participant_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='participant_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='team_lead_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
